version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0.0-stretch
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./ASPNETCorePractice.IdentityServer.sln && dotnet publish ./ASPNETCorePractice.IdentityServer.sln -c Release -o ./obj/Docker/publish"
